GarmentsManagementApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'GarmentsManagementApp'
urlpatterns = [
    path('',views.home),
    path('login/',views.admin_login,name='login'),
    path('logout/',views.admin_logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addEmployee/',views.AddEmployee,name='AddEmployee'),
    path('employees/',views.ShowEmployees,name='ShowEmployee'),
    path('editEmployee/<int:pk>/',views.EditEmployee,name='editEmployee'),
    path('deleteEmployee/<int:pk>/',views.deleteEmployee,name='deleteEmployee'),

    path('createproduct/',views.AddProduct,name='AddProduct'),
    path('ShowProducts/',views.ShowProducts,name='ShowProducts'),
    path('editProduct/<int:pk>/',views.editProduct,name='editProduct'),
    path('deleteProduct/<int:pk>/',views.deleteProduct,name='deleteProduct'),

    path('addGarment/',views.AddGarment,name='AddGarment'),
    path('ShowGarments/',views.ShowGarments,name='ShowGarments'),
    path('editGarment/<int:pk>/',views.EditGarment,name='editGarment'),
    path('deleteGarment/<int:pk>/',views.deleteGarment,name='deleteGarment'),

    path('createorder/',views.createOrder,name='createOrder'),
    path('showorders/',views.ShowOrders,name='ShowOrders'),
    path('deleteOrder/<int:pk>/', views.deleteOrder, name='deleteOrder'),
    path('forward/<int:pk>/',views.forward,name='forwardOrder'),
    path('reject/<int:pk>/',views.reject,name='rejectOrder'),
    path('showdepartments/',views.showdepartments,name='ShowDepartments'),
    path('showSuppliers/',views.showSuppliers,name='ShowSuppliers'),
    path('showShipments/',views.showShipments,name='showShipments'),
    path('calculateDate/',views.calculateDeliveryDate,name='calculateDate'),
    path('collaboration/', views.collab),
    path('aboutUs/', views.abt),
]

GarmentsProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('GarmentsManagementApp.urls')),
    path('admin', admin.site.urls),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/AddEmployee.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true"><br><br>
        <label for="EmpId"> Employee Id </label>
            <input type="text" name="EmpId" id="EmpId" required="true"><br><br>
            <label for="department"> department</label>
            <select name="department" id="department" required="true">
               {% for item in depts %}
                   <option value= {{ item.id }} > {{ item.Name }} </option>
                {% endfor %}
            </select><br><br>
            <label for="salary"> Salary</label>
            <input type="number" name="salary" id="salary" required="true"><br><br>
            <label for="phone"> Phone No </label>
            <input type="text" name="phone" id="phone" required="true"><br><br>
            <label for="address"> Address </label>
            <input type="text" name="address" id="address" required="true"><br><br>
            <label for="status"> Status </label>
            <input type="text" name="status" id="status" required="true"><br><br>
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/AddGarment.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true"><br><br>
            <label for="type"> Type</label>
            <input type="text" name="type" id="type" required="true"><br><br>
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/EditEmployee.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST" action="/editEmployee/{{ data.id }}/">
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true" value="{{ data.Name }}"><br><br>
            <label for="department"> department</label>
            <select name="department" id="department" required="true">
               {% for item in depts %}
                   <option value= {{ item.id }} > {{ item.Name }} </option>
                {% endfor %}
            </select><br><br>
            <label for="salary"> Salary</label>
            <input type="number" name="salary" id="salary" required="true" value="{{ data.salary }}"><br><br>

            <input type="text" name="phone" id="phone" required="true" value="{{ data.Phone }}"><br><br>
            <label for="address"> Address </label>
            <input type="text" name="address" id="address" required="true" value="{{ data.address }}"><br><br>
            <label for="status"> Status </label>
            <input type="text" name="status" id="status" required="true" value="{{ data.status }}"><br><br>

            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}

templates/EditGarment.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST" >
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true" value="{{ data.name }}"><br><br>
             <label for="type"> Type</label>
            <input type="text" name="type" id="type" required="true" value="{{ data.type }}"><br><br>
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}

templates/HomePage.html
{% extends 'index.html' %}
{% block content %}
{% load static %}

<style>


        body{
            background-image: url("{% static 'images/P.jpg' %}");
            {#margin: 50px;#}
            {#padding: 100px;#}
            background-attachment: fixed;
            background-position: right;
            background-repeat: no-repeat;
        }

        .container{
            background-repeat: no-repeat;
            background-size: cover;
            background-size: 50%;
            position: relative;
            width: 100%;
            height: 60px;
        }

        .site_title{
            position: center;
            top: 50%;
            left: 15%;
            -webkit-transform: translate(-50);
            -ms-transform: translateY(50%);
            transform: translateY(50%);
            z-index: 2;
            font-family: sans_serif;
        }

        .site_title h1 {
            font-size: 60px;
            color: #c93636;
            text-align: left;
            margin: 0;
            position: left;
        }

        .site_title p{
            font-size: 20px;
            color: #c68181;
            text-align: left;
            margin: 0;
            letter-spacing: 6px;
            margin-top: 5px;
            position: center;
        }


        h6{
            margin: 2%;

        }
    </style>
<html>
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport"#}
{#          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#    <title></title>#}
{##}
{#</head>#}
<body  >
<div class="container">
    <div class="site_title">
        <h1>RMG</h1>
        <p style="text-align:left"> Biggest Industry in Bangladesh</p>
    </div>
    <div class="overlay"></div>
</div><br>
<h6>
    <br><br><br><br><br>

    The readymade garments industry acts as a catalyst for the development of Bangladesh. <br>
    The"Made in Bangladesh" tag has also brought glory for the country, making it a prestigious <br>
    brand across the globe. Bangladesh, which was once termed by cynics a "bottomless basket" has now<br>
    become a "basket full of wonders." The country with its limited resources has been maintaining 6%<br>
    annual average GDP growth rate and has brought about remarkable social and human development.<br><br>

    After the independence in 1971, Bangladesh was one of poorest countries in the world. No major<br>
    industries were developed in Bangladesh, when it was known as East Pakistan, due to discriminatory<br>
    attitude and policies of the government of the then West Pakistan. So, rebuilding the war-ravaged<br>
    country with limited resources appeared to be the biggest challenge.<br><br>

    The industry that has been making crucial contribution to rebuilding the country and its economy<br>
    is none other than the readymade garment (RMG) industry which is now the single biggest export <br>
    earner for Bangladesh. The sector accounts for 83% of total export earnings of the country.<br><br>

    The apparel industry of Bangladesh started its journey in the 1980s and has come to the position it <br>
    is in today. The late NuroolQuader Khan was the pioneer of the readymade garment industry in <br>
    Bangladesh. He had a vision of how to transform the country. In 1978, he sent 130 trainees to<br>
    South Korea where they learned how to produce readymade garments.<br><br>

    With those trainees, he set up the first factory "Desh Garments"  to produce garments for export.<br>
    At the same time, the late Akhter Mohammad Musa of Bond Garments, the late Mohammad <br>
    Reazuddin of Reaz Garments, MdHumayun of Paris Garments, Engineer Mohammad Fazlul Azim of <br>
    Azim Group, Major (Retd) Abdul Mannan of Sunman Group, M Shamsur Rahman of Stylecraft Limited,<br>
    the first President of BGMEA, AM Subid Ali of Aristocrat Limited also came forward and established <br>
    some of the first garment factories in Bangladesh.<br><br>

    Following their footsteps, other prudent and hardworking entrepreneurs started RMG factories <br>
    in the country. Since then, Bangladeshi garment industry did not need to look behind. Despite <br>
    many difficulties faced by the sector over the past years, it has carved a niche in<br>
    world market and kept continuing to show robust performance.<br><br>

</h6>

</body>
</html>


{% endblock %}

templates/ShowEmployees.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #26a5b6;
  color: white;
}
</style>

<div align="center">
    <form method="POST">
        {% csrf_token %}
        <br><br><br><br>
        <label for="searchname"> Search Employee </label>
        <input type="text" name="searchname" id="searchname" placeholder="Enter Employee Name">
        <input type="submit" value="Search">
    </form>
</div>

<div align="center">
    <form method="POST">
        {% csrf_token %}
        <br><br>
        <label for="searchid"> Search Employee </label>
        <input type="text" name="searchid" id="searchid" placeholder="Enter Employee id">
        <input type="submit" value="Search"><br><br><br>
    </form>
</div>
<table id="customers">
  <tr>
      <th>Id</th>
    <th>Name</th>
    <th>Department</th>
    <th>Salary</th>
      <th>Phone No</th>
      <th>Address</th>
      <th>Status</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
        <td>{{ item.EmployeeID }}</td>
            <td>{{ item.Name }}</td>
            <td>{{ item.department.Name }}</td>
            <td>{{ item.salary }}</td>
            <td>{{ item.Phone }}</td>
            <td>{{ item.address }}</td>
            <td>{{ item.status }}</td>
            <td> <a type="button" class="alert-dark" href="{% url 'GarmentsManagementApp:editEmployee' pk=item.id %}">Edit    [] </a> <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteEmployee' pk=item.id %}" onclick="alert('Are you sure?')">Delete</a></td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/ShowGarments.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #26a5b6;
  color: white;
}
</style>


<table id="customers">
  <tr>

    <th>Id</th>
    <th>Name</th>
    <th>Type</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.type }}</td>

            <td> <a type="button" class="alert-dark" href="{% url 'GarmentsManagementApp:editGarment' pk=item.id %}">Edit    [] </a> <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteGarment' pk=item.id %}" onclick="alert('Are you sure?')">Delete</a></td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/ShowOrders.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
    text-align: center;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers button {
    background-color: #50c764
}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: center;
  background-color: #26a5b6;
  color: white;
}
</style>
</head>
<body>

<table id="customers">
  <tr>
      <th>OrderID</th>
    <th>Customer Name</th>
    <th>Phone</th>
    <th>Product Name</th>
      <th>Product Description</th>
      <th>Garments Name</th>
      <th>Status</th>
      <th>Department</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
            <td>{{ item.OrderID }}</td>
            <td>{{ item.CustomerName}}</td>
            <td>{{ item.CustomerPhn }}</td>
            <td>{{ item.product.Name }}</td>
            <td>{{ item.product.description }}</td>
            <td>{{ item.product.garment.name }}</td>
            <td>{{ item.Status }}</td>
            <td>{{ item.department.Name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.TotalPrice }}</td>
            <td>  <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteOrder' pk=item.id  %}" onclick="alert('Are you sure?')">Delete</a> <br>

            {% if item.Status != 'Shipped' %}
                    <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:forwardOrder' pk=item.id  %}" onclick="alert('Are you sure?')">Forward to Next Dept.</a><br>
               {% if item.department.Name != 'Production' %}
                <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:rejectOrder' pk=item.id  %}" onclick="alert('Are you sure?')">Send Back to Prev. Dept.</a>
                {% endif %}
            {% endif %}
            </td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/ShowProducts.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
     text-align: -webkit-center;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;

  background-color: #26a5b6;
  color: white;
}
</style>
</head>
<body>

<table id="customers">
  <tr>
    <th>Product ID</th>
    <th>Name</th>
    <th>Garment Company</th>
    <th>Price</th>
      <th>Current Stock</th>
      <th>Description</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
            <td>{{ item.product_id }}</td>
            <td>{{ item.Name }}</td>
            <td>{{ item.garment.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.current_stock }}</td>
            <td>{{ item.description }}</td>
            <td> <a type="button" class="alert-dark" href="{% url 'GarmentsManagementApp:editProduct' pk=item.id %}">Edit    [] </a> <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteProduct' pk=item.id %}" onclick="alert('Are you sure?')">Delete</a></td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/calculateDelivery.html
{% extends 'index.html' %}
{% block content %}

    <style>
    #data {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        font-size: xx-large;
        }
    </style>
    <div align="center">
        <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}

            <label for="product"> Product </label>
            <select name="product" id="product" required="true">
                {% for i in products %}
                <option value="{{ i.id }}">{{ i.Name }} |Garment:- {{ i.garment.name }}|Description:- {{ i.description }}|Price:-{{ i.price }}</option>
                {% endfor %}
                </select><br><br>
            <label for="quant"> Enter Quantity</label>
            <input type="number" name="quant" id="quant" required="true" ><br><br>
            <br><br>
            <input type="submit" value="Calculate">
        <br><br><br>
        <label for="data"> Estimated shipment date : </label>
        <div id="data">
            {{ delivarydate }}
        </div>
        </form>
    </div>




{% endblock %}

templates/createOrder.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}
            <label for="customer_name">Customer Name </label>
            <input type="text" name="customer_name" id="customer_name" required="true"><br><br>

            <label for="OrdId"> Order Id </label>
            <input type="text" name="OrdId" id="OrdId" required="true"><br><br>

            <label for="customer_phn">Customer Phone </label>
            <input type="text" name="customer_phn" id="customer_phn" required="true"><br><br>

            <select name="product" id="product" required="true">
                {% for i in list %}
                <option value="{{ i.id }}">{{ i.Name }} |Garment:- {{ i.garment.name }}|Description:- {{ i.description }}|Price:-{{ i.price }}</option>
                {% endfor %}
                </select><br><br>

            <label for="quantity"> Quantity</label>
            <input type="number" name="quantity" id="quantity" required="true"><br><br>
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Garments Management</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="icon" size="32x32" href="{% static 'assets/imgicon.png' %}">
</head>

<body>
<nav class="navbar navbar-light navbar-expand-md text-monospace text-nowrap text-truncate navigation-clean">
    <div class="container"><img src="../static/images/l5.png" width="90" height="90" a
            class="navbar-brand text-monospace text-nowrap text-truncate text-break text-dark flash animated" href="#">Garments
        Management </a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div
                class="collapse navbar-collapse bounce animated" id="navcol-1">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                            href="/">Home</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                            href="/aboutUs/">About Us</a></li>

                <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                            href="/collaboration/">Collaboration</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                                href="/dashboard/">Dashboard</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                                href="/logout/">Logout</a></li>
                {% else %}
                    <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                                href="/login/">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>



{% block content %}
{% endblock %}




<div class="footer-basic">
    <footer>
        <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i
                class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a
                href="https://www.facebook.com/"><i class="icon ion-social-facebook"></i></a></div>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="#">Home</a></li>
            <li class="list-inline-item"><a href="#">Services</a></li>
            <li class="list-inline-item"><a href="#">About</a></li>
            <li class="list-inline-item"><a href="#">Terms</a></li>
            <li class="list-inline-item"><a href="#">Contact Us</a></li>
        </ul>
        <p class="copyright">FBN Industries & ltd © 2020</p>
    </footer>
</div>
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/bs-init.js' %}"></script>
</body>

</html>

templates/login.html
{% extends 'index.html' %}
{% block content %}
<br><br><br><br><br><br><br><br><br>
    <div align="center">

    <form method="POST">
         {% csrf_token %}
        <label for="id_username"> Enter Username </label>
        <input type="text" name="username" id="id_username" placeholder="UserName"> <br><br>
        <label for="id_pass"> Enter password</label>
        <input type="password" name="password" id="id_pass" placeholder="password"><br><br>
        <input type="submit">
    </form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    <br><br><br>
</div>
{% endblock %}

templates/showSupplier.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
    text-align: center;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers button {
    background-color: #50c764
}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: center;
  background-color: #26a5b6;
  color: white;
}
</style>
</head>
<body>

<table id="customers">
  <tr>
      <th>name</th>
     <th>Company_Name</th>
   <th>Company_Address</th>
     <th>phone</th>
     <th>garment</th>
     <th>deliveryDate</th>
  </tr>

    {% for item in list %}
        <tr>
            <td>{{ item.name}}</td>
            <td>{{ item.Company_Name }}</td>
            <td>{{ item.Company_Address }}</td>
            <td>{{ item.phone }}</td>
        <td>{{ item.garment.Name }}</td>
        <td>{{ item.deliveryDate }}</td>
        </tr>
    {% endfor %}


</table>
{% endblock %}